# Generated by Django 5.1.1 on 2024-09-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companies_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=50)),
                ('dividend_yield', models.CharField(max_length=50)),
                ('eps', models.CharField(max_length=50)),
                ('ticker_symbol', models.CharField(max_length=50)),
                ('market', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lSIN', models.CharField(max_length=100)),
            ],
        ),
    ]
